[package]
name = "gotrue-rs"
version = "0.1.0"
edition = "2021"
authors = [
    "Harry Bairstow <harry@walletconnect.com>"
]

[dependencies]
jsonwebtoken = {version = "8", default-features = false }
serde = {version = "1.0", features = ["derive"] }